name: 品川区予約可能一覧取得 (GitActionsArenaReserveService)

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # 毎日0時 (UTC)：日本時間9:00に実行

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: コードをチェックアウト
        uses: actions/checkout@v3

      - name: Java17をセットアップ
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Chromeをインストール
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Chromeのバージョンを取得
        id: get_chrome_version
        run: |
          version=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
          echo "chrome_version=$version" >> $GITHUB_OUTPUT

      - name: ChromeDriverをセットアップ
        uses: nanasess/setup-chromedriver@v2
        with:
          chromedriver-version: ${{ steps.get_chrome_version.outputs.chrome_version }}

      - name: パスを取得して環境変数にセット
        id: get_paths
        run: |
          CHROME_PATH=$(which google-chrome)
          CHROMEDRIVER_PATH=$(which chromedriver)
          echo "CHROME_PATH=$CHROME_PATH" >> $GITHUB_OUTPUT
          echo "CHROMEDRIVER_PATH=$CHROMEDRIVER_PATH" >> $GITHUB_OUTPUT

      - name: パスの確認（デバッグ用）
        run: |
          echo "Chrome: ${{ steps.get_paths.outputs.CHROME_PATH }}"
          echo "ChromeDriver: ${{ steps.get_paths.outputs.CHROMEDRIVER_PATH }}"

      - name: Mavenパッケージをビルド
        run: mvn clean package

      - name: 処理を実行
        env:
          CHROME_BINARY_PATH: ${{ steps.get_paths.outputs.CHROME_PATH }} # Chromeのパス
          CHROMEDRIVER_PATH: ${{ steps.get_paths.outputs.CHROMEDRIVER_PATH }} # ChromeDriverのパス
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }} # LINE Notifyのアクセストークン
          NOTIFY_LINE_ID: ${{ secrets.NOTIFY_LINE_ID }} # LINE Notifyの通知先ID
        run: mvn exec:java -Dexec.mainClass="com.copel.productpackages.arena.selenium.service.ArenaReservableSearchServiceShinagawa" -Dexec.classpathScope=runtime
